# This line must fail the first real restricted run; Claude must inspect stderr and repair it.
stop("WB_INTENTIONAL_ERROR: repair this line after reading command stderr")
data <- read.csv("wb_inputs/tomato.csv", stringsAsFactors = FALSE)
stopifnot(nrow(data) == 6, all(c("plant", "temperature", "yield") %in% names(data)))
model <- lm(yield ~ temperature, data = data)
result <- transform(data, prediction = as.numeric(predict(model)))
write.csv(result, "result.csv", row.names = FALSE, fileEncoding = "UTF-8")
saveRDS(model, "model.rds")
png("plot.png", width = 800, height = 600)
plot(data$temperature, data$yield, xlab = "Temperature", ylab = "Tomato yield", pch = 19)
abline(model, col = "tomato", lwd = 2)
dev.off()
utils::zip("result_bundle.zip", c("result.csv", "model.rds", "plot.png"), flags = "-j")
stopifnot(all(file.exists(c("result.csv", "model.rds", "plot.png", "result_bundle.zip"))))
